{% set name = "laszip" %}
{% set version = "3.4.3" %}
{% set sha256 = "862715affa00609b78b4f469ab5529fee659c597efd40b5006b4305dd56c22d3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ name }}/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and py!=36]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
  run:

test:
  commands:
    - test -d $PREFIX/include/laszip  # [not win]
    - if not exist %LIBRARY_INC%\\laszip exit 1  # [win]

about:
  home: https://www.laszip.org
  license: LGPL-2.0
  license_family: LGPL
  license_file: COPYING
  summary: 'LASzip is a compression library for compressing ASPRS LAS format'
  description: |
    Quickly turns bulky LAS files into compact LAZ files without information loss.
  doc_url: https://www.laszip.org/
  dev_url: https://github.com/LASzip/LASzip

extra:
  recipe-maintainers:
    - chambbj
    - hobu
