{% set name = "laszip" %}
{% set version = "3.4.4" %}
{% set sha256 = "41f826848ff106f471b134224f58075ac8e36a62b6ba0ad75be8a8c191bdba4b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: laszip-src-{{ version }}.tar.gz
  url: https://github.com/{{ name }}/{{ name }}/releases/download/{{ version }}/laszip-src-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win and py!=36]

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
  run:

test:
  commands:
    - test -d $PREFIX/include/laszip  # [not win]
    - if not exist %LIBRARY_INC%\\laszip exit 1  # [win]

about:
  home: https://www.laszip.org
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: 'LASzip is a compression library for compressing ASPRS LAS format'
  description: |
    Quickly turns bulky LAS files into compact LAZ files without information loss.
  doc_url: https://www.laszip.org/
  dev_url: https://github.com/LASzip/LASzip

extra:
  recipe-maintainers:
    - chambbj
    - hobu
